<?php

namespace WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatoRepository extends EntityRepository
{
}
